-- MySQL Script generated by MySQL Workbench
-- Sat May 16 18:54:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema farmacia_generica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema farmacia_generica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmacia_generica` DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci ;
USE `farmacia_generica` ;

-- -----------------------------------------------------
-- Table `farmacia_generica`.`tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia_generica`.`tipo_documento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia_generica`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia_generica`.`genero` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia_generica`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia_generica`.`ciudad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia_generica`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia_generica`.`tipo_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia_generica`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia_generica`.`login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `tipo_usuario_id` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  INDEX `fk_login_tipo_usuario1_idx` (`tipo_usuario_id` ASC),
  CONSTRAINT `fk_login_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `farmacia_generica`.`tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia_generica`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia_generica`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `tipo_documento_id` INT NOT NULL,
  `numero_documento` INT NOT NULL,
  `genero_id` INT NOT NULL,
  `codigo_validacion` INT NOT NULL,
  `ciudad_id` INT NOT NULL,
  `login_id` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_tipo_documento1_idx` (`tipo_documento_id` ASC),
  INDEX `fk_cliente_genero1_idx` (`genero_id` ASC),
  INDEX `fk_cliente_ciudad1_idx` (`ciudad_id` ASC),
  UNIQUE INDEX `numero_documento_UNIQUE` (`numero_documento` ASC),
  INDEX `fk_cliente_login1_idx` (`login_id` ASC),
  CONSTRAINT `fk_cliente_tipo_documento1`
    FOREIGN KEY (`tipo_documento_id`)
    REFERENCES `farmacia_generica`.`tipo_documento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_genero1`
    FOREIGN KEY (`genero_id`)
    REFERENCES `farmacia_generica`.`genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_ciudad1`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `farmacia_generica`.`ciudad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_login1`
    FOREIGN KEY (`login_id`)
    REFERENCES `farmacia_generica`.`login` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia_generica`.`puntos_redimibles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia_generica`.`puntos_redimibles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `puntos` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_puntos_redimibles_cliente1_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_puntos_redimibles_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `farmacia_generica`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia_generica`.`estante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia_generica`.`estante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
UNIQUE INDEX `NIT_nombre` (`nombre` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia_generica`.`laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia_generica`.`laboratorio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,  
  `estado` VARCHAR(45) NOT NULL,
UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),

  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia_generica`.`tipo_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia_generica`.`tipo_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia_generica`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia_generica`.`proveedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `NIT` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `ciudad_id` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `NIT_UNIQUE` (`NIT` ASC),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  INDEX `fk_proveedor_ciudad1_idx` (`ciudad_id` ASC),
  CONSTRAINT `fk_proveedor_ciudad1`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `farmacia_generica`.`ciudad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia_generica`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia_generica`.`inventario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `miligramos` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `fecha_vencimiento` DATE NOT NULL,
  `lote` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `estante_id` INT NOT NULL,
  `laboratorio_id` INT NOT NULL,
  `tipo_producto_id` INT NOT NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inventario_estante1_idx` (`estante_id` ASC),
  INDEX `fk_inventario_laboratorio2_idx` (`laboratorio_id` ASC),
  INDEX `fk_inventario_tipo_producto1_idx` (`tipo_producto_id` ASC),
  INDEX `fk_inventario_proveedor1_idx` (`proveedor_id` ASC),
  CONSTRAINT `fk_inventario_estante1`
    FOREIGN KEY (`estante_id`)
    REFERENCES `farmacia_generica`.`estante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_laboratorio2`
    FOREIGN KEY (`laboratorio_id`)
    REFERENCES `farmacia_generica`.`laboratorio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_tipo_producto1`
    FOREIGN KEY (`tipo_producto_id`)
    REFERENCES `farmacia_generica`.`tipo_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_proveedor1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `farmacia_generica`.`proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia_generica`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia_generica`.`empleado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `tipo_documento_id` INT NOT NULL,
  `numero_documento` VARCHAR(45) NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `genero_id` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `login_id` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empleado_tipo_documento1_idx` (`tipo_documento_id` ASC),
  INDEX `fk_empleado_genero1_idx` (`genero_id` ASC),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  UNIQUE INDEX `numero_documento_UNIQUE` (`numero_documento` ASC),
  INDEX `fk_empleado_login1_idx` (`login_id` ASC),
  CONSTRAINT `fk_empleado_tipo_documento1`
    FOREIGN KEY (`tipo_documento_id`)
    REFERENCES `farmacia_generica`.`tipo_documento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_genero1`
    FOREIGN KEY (`genero_id`)
    REFERENCES `farmacia_generica`.`genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_login1`
    FOREIGN KEY (`login_id`)
    REFERENCES `farmacia_generica`.`login` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia_generica`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia_generica`.`venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_venta` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `valor_total` DOUBLE NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `empleado_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_venta_empleado1_idx` (`empleado_id` ASC),
  INDEX `fk_venta_cliente1_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_venta_empleado1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `farmacia_generica`.`empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `farmacia_generica`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia_generica`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia_generica`.`detalle_venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `inventario_id` INT NOT NULL,
  `venta_id` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalle_venta_inventario1_idx` (`inventario_id` ASC),
  INDEX `fk_detalle_venta_venta1_idx` (`venta_id` ASC),
  CONSTRAINT `fk_detalle_venta_inventario1`
    FOREIGN KEY (`inventario_id`)
    REFERENCES `farmacia_generica`.`inventario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_venta_venta1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `farmacia_generica`.`venta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia_generica`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia_generica`.`administrador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `tipo_documento_id` INT NOT NULL,
  `numero_documento` VARCHAR(45) NOT NULL,
  `genero_id` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `login_id` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empleado_tipo_documento1_idx` (`tipo_documento_id` ASC),
  INDEX `fk_empleado_genero1_idx` (`genero_id` ASC),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  UNIQUE INDEX `numero_documento_UNIQUE` (`numero_documento` ASC),
  INDEX `fk_administrador_login1_idx` (`login_id` ASC),
  CONSTRAINT `fk_empleado_tipo_documento10`
    FOREIGN KEY (`tipo_documento_id`)
    REFERENCES `farmacia_generica`.`tipo_documento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_genero10`
    FOREIGN KEY (`genero_id`)
    REFERENCES `farmacia_generica`.`genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_administrador_login1`
    FOREIGN KEY (`login_id`)
    REFERENCES `farmacia_generica`.`login` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- Datos parametricos

INSERT INTO `tipo_documento` (`id`, `nombre`) VALUES ('1', 'C�dula de ciudadan�a'), ('2', 'Pasaporte');

INSERT INTO `tipo_usuario` (`id`, `nombre`) VALUES ('1', 'Administrador'), ('2', 'Empleado'), ('3', 'Cliente');

INSERT INTO `tipo_producto` (`id`, `nombre`) VALUES ('1', 'Medicamento'), ('2', 'Producto');

INSERT INTO `genero` (`id`, `nombre`) VALUES ('1', 'Hombre'), ('2', 'Mujer');

INSERT INTO `ciudad` (`id`, `nombre`) VALUES ('1', 'Armenia'), ('2', 'Bogot�'), ('3', 'Medell�n'), ('4', 'Cali'), ('5', 'Barranquilla'), ('6', 'Cartagena de Indias'), ('7', 'Soacha'), ('8', 'C�cuta'), ('9', 'Soledad'), ('10', 'Bucaramanga'), ('11', 'Bello'), ('12', 'Villavicencio'), ('13', 'Ibagu�'), ('14', 'Santa Marta'), ('15', 'Valledupar'), ('16', 'Manizales'), ('17', 'Pereira'), ('18', 'Monter�a'), ('19', 'Neiva'), ('20', 'Pasto');

INSERT INTO `estante` (`id`, `nombre`, `estado`, `descripcion`) VALUES ('1', 'Por defecto', 'activo', 'Este es el estante por defecto donde se encuentran los productos a los cuales no se les ha definido un estante en especifico'), ('2', 'Medicamentos posconsumo', 'activo', 'Este es el estante donde se almacenaran los medicamentos posconsumo ');

INSERT INTO `login` (`id`, `usuario`, `password`, `tipo_usuario_id`, `estado`) VALUES ('1', 'admin', 'admin', '1', 'activo');

INSERT INTO `login` (`id`, `usuario`, `password`, `tipo_usuario_id`, `estado`) VALUES ('2', 'cliente', 'cliente', '3', 'activo');

INSERT INTO `administrador` (`id`, `nombres`, `apellidos`, `tipo_documento_id`, `numero_documento`, `genero_id`, `estado`, `login_id`, `correo`) VALUES ('1', 'Admin', 'por defecto', '1', '1234567890', '1', 'activo', '1', 'admin@gmail.com');

INSERT INTO `cliente` (`id`, `nombres`, `apellidos`, `tipo_documento_id`, `numero_documento`, `genero_id`, `codigo_validacion`, `ciudad_id`, `login_id`, `correo`) VALUES ('1', 'Cliente ', 'no registrado', '1', '0000000000', '2', '0000', '2', '2', 'clienteSinRegistro@gmail.com');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
